export const types ={
    getListTopAnimes: '[animeStreaming] show all top animes',
    getListWithGenre: '[animeStreaming] show list with genre animes',
    getlistCharactersStaff: '[animeStreaming] show list with staff',
    getListPictures: '[animeStreaming] show list promotional cover',
    getListVideos: '[animeStreaming] show promotional trailer',
    getListEpisodes: '[animeStreaming] show list with episodes',
    getListNews: '[animeStreaming] show list with news',
    getMoreInfo: '[animeStreaming] show more information of this anime',
    getNameAndDate: '[animeStreaming] get name of the anime and date by card',
    getSearchAnime: '[animeStreaming] show list with anime by names',
    getTitleOfListAnime: '[animeStreaming] show mame list',
    getClearAllDetail: '[animeStreaming] clear all boxes containing the anime details',
    getAddAnimeFavorite: '[animeStreaming] add anime at favorite list',
    getRemoveAnimeFavorite: '[animeStreaming] remove anime at favorite list',
}